### ISSUE TITLE
Failed to install BitWatts

### ISSUE THREAD

**Issue by stefanos1316** [Spirals-Team/bitwatts#3]
Hello, 

I am trying to build BitWatts using sbt and I get the following error: 

`[error] (*:update) sbt.ResolveException: unresolved dependency: org.scala-lang#scala-library;2.10.5: configuration not public in org.scala-lang#scala-library;2.10.5: 'test'. It was required from org.scala-lang#scala-compiler;2.10.4 test
`
my  scala version 2.10.4 is:

`[root@192 bitwatts]# scala -version
Scala code runner version 2.10.4 -- Copyright 2002-2013, LAMP/EPFL
`
Any ideas how to work around it?

**Comment by mcolmant** [comment]
Hello, 

Thanks for using BitWatts.

I tried from scratch to rebuild BitWatts on my laptop, and it works without any problem.
I do not think that this problem is linked to scala or sbt version (everything is set via configuration files).

Can you try to re-clone the project, re-built everything and send me all the execution traces?
Otherwise, BitWatts is already [released](https://github.com/Spirals-Team/bitwatts/releases/tag/1.1) and ready to use.

**Comment by stefanos1316** [comment]
Hello Colmant,

Thanks for the swift reply. 
I tried to download and use the linked release and runs fine. 

Could you also please answer this for me? 
I am using this specific command 
`./bitwatts modules procfs-cpu-simple monitor --frequency 1000 --targets 3420 --agg max --file testing_bitwatts.dat duration 100
`
The PID 3420 is a compiler.compiler application form the SPECjvm2008 benchmark suite; that stresses the CPU at  100%. 
Nevertheless, I do not see any consumption in my results file, i.e., testing_bitwatts.dat 
This is the output:
`muid=5c48cab3-c5d5-4e64-b874-6472e4e538cd;timestamp=1487623039078;targets=3420;devices=cpu;power=0.0
muid=5c48cab3-c5d5-4e64-b874-6472e4e538cd;timestamp=1487623040067;targets=3420;devices=cpu;power=0.0
muid=5c48cab3-c5d5-4e64-b874-6472e4e538cd;timestamp=1487623041068;targets=3420;devices=cpu;power=0.0
muid=5c48cab3-c5d5-4e64-b874-6472e4e538cd;timestamp=1487623042078;targets=3420;devices=cpu;power=0.0
muid=5c48cab3-c5d5-4e64-b874-6472e4e538cd;timestamp=1487623043068;targets=3420;devices=cpu;power=0.0
muid=5c48cab3-c5d5-4e64-b874-6472e4e538cd;timestamp=1487623044068;targets=3420;devices=cpu;power=0.0
muid=5c48cab3-c5d5-4e64-b874-6472e4e538cd;timestamp=1487623045078;targets=3420;devices=cpu;power=0.0
muid=5c48cab3-c5d5-4e64-b874-6472e4e538cd;timestamp=1487623046078;targets=3420;devices=cpu;power=0.0
muid=5c48cab3-c5d5-4e64-b874-6472e4e538cd;timestamp=1487623047068;targets=3420;devices=cpu;power=0.0
muid=5c48cab3-c5d5-4e64-b874-6472e4e538cd;timestamp=1487623048067;targets=3420;devices=cpu;power=0.0
muid=5c48cab3-c5d5-4e64-b874-6472e4e538cd;timestamp=1487623049066;targets=3420;devices=cpu;power=0.0
muid=5c48cab3-c5d5-4e64-b874-6472e4e538cd;timestamp=1487623050068;targets=3420;devices=cpu;power=0.0
muid=5c48cab3-c5d5-4e64-b874-6472e4e538cd;timestamp=1487623051068;targets=3420;devices=cpu;power=0.0
muid=5c48cab3-c5d5-4e64-b874-6472e4e538cd;timestamp=1487623052068;targets=3420;devices=cpu;power=0.0
muid=5c48cab3-c5d5-4e64-b874-6472e4e538cd;timestamp=1487623053068;targets=3420;devices=cpu;power=0.0
` 
Am I doing something wrong here?

Kind regards,
Stefanos Georgiou

**Comment by mcolmant** [comment]
Hi,

What exactly do you want to monitor?
The first purpose of BitWatts is to be used inside virtualized environments.
If you want to follow "native" processes, please consider [PowerAPI](https://github.com/Spirals-Team/powerapi).

A wiki and a chat (Gitter button in the README) has been created to help the community with PowerAPI.
Do not hesitate to browse the messages, several useful explanations are already provided inside this chatroom.

**Comment by stefanos1316** [comment]
Hello, 

What I would like to monitor is the power consumption of a specific task such as the 3420, in this case. 
This task is not running inside the host environment but inside a VM. 
Can I do the work using the BitWatts?

**Comment by mcolmant** [comment]
Hello,

Ok, so you can use BitWatts for monitoring a process running inside a VM.
A specific setup is then required to use BitWatts.
You have to use Qemu and KVM for the virtualization layer.
Please consider to read our [paper](https://hal.inria.fr/hal-01130030) to have more details.

**Comment by stefanos1316** [comment]
Oh, great! 
Thanks a lot :)
